let test = [
  "Card1.png",
  "brian1.png",
  "factor2.png",
  "genotype4.png",
  "horse2.png",
  "meta2.png",
  "proia1.png",
  "room2.png",
  "Cipher1.png",
  "brian2.png",
  "factor3.png",
  "herring1.png",
  "login.png",
  "meta3.png",
  "proia2.png",
  "stock1.png",
  "Cipher2.png",
  "brian3.png",
  "factor4.png",
  "herring2.png",
  "login3.png",
  "name2.png",
  "qrcode.png",
  "stock2.png",
  "Cipher3.png",
  "chenko1.png",
  "genotype1.png",
  "herring3.png",
  "master1.png",
  "name3543.png",
  "qrcode2.png",
  "book1.png",
  "chenko2.png",
  "genotype2.png",
  "herring4.png",
  "master2.png",
  "newspaper1.png",
  "redscrible1.png",
  "book2.png",
  "factor1.png",
  "genotype3.png",
  "horse1.png",
  "meta1.png",
  "newspaper2.png",
  "room1.png",
];

let test2 = {};

for (let i in test) {
  test2[test[i].split(".")[0]] = {
    name: test[i].split(".")[0],
    sizeX: 150,
    sizeY: 200,
    start: false,
    type: "png",
  };
}
console.log(JSON.stringify(test2));
